      ; Test 9: Create context
      (print-string "Test 9: Create context")
      (assert-equal current-context NULL "Initial context should be NULL")
      (define-var test-ctx (new-context NULL (tag-int 42) (tag-int 50000) 3))
      (assert-equal (untag-int (context-get-receiver test-ctx)) 42 "Context receiver should be 42")
      (assert-equal (untag-int (context-get-method test-ctx)) 50000 "Context method should be 50000")
      (print-string "  PASSED")

      ; Test 10: Context temporaries
      (print-string "Test 10: Context temporaries")
      (context-temp-at-put test-ctx 0 (tag-int 10))
      (context-temp-at-put test-ctx 1 (tag-int 20))
      (context-temp-at-put test-ctx 2 (tag-int 30))
      (assert-equal (untag-int (context-temp-at test-ctx 0)) 10 "Temp 0 should be 10")
      (assert-equal (untag-int (context-temp-at test-ctx 1)) 20 "Temp 1 should be 20")
      (assert-equal (untag-int (context-temp-at test-ctx 2)) 30 "Temp 2 should be 30")
      (print-string "  PASSED")

      ; Test 11: Message send (context switching)
      (print-string "Test 11: Message send (context switching)")
      (define-var args-addr (malloc 3))
      (poke args-addr (tag-int 2))
      (poke (+ args-addr 1) (tag-int 100))
      (poke (+ args-addr 2) (tag-int 200))
      (define-var msg-ctx (message-send (tag-int 42) (tag-int 40) args-addr 2))
      (assert-equal current-context msg-ctx "Current context should be new context")
      (assert-equal (untag-int (context-get-receiver msg-ctx)) 42 "Message receiver should be 42")
      (assert-equal (untag-int (context-get-method msg-ctx)) 50000 "Should find SmallInteger + method")
      (assert-equal (untag-int (context-temp-at msg-ctx 0)) 100 "First arg should be 100")
      (assert-equal (untag-int (context-temp-at msg-ctx 1)) 200 "Second arg should be 200")
      (print-string "  PASSED")

      ; Test 12: Nested message sends
      (print-string "Test 12: Nested message sends")
      (define-var outer-ctx current-context)
      (define-var args2-addr (malloc 2))
      (poke args2-addr (tag-int 1))
      (poke (+ args2-addr 1) (tag-int 5))
      (define-var inner-ctx (message-send (tag-int 10) (tag-int 41) args2-addr 1))
      (assert-equal (context-get-sender inner-ctx) outer-ctx "Inner sender should be outer context")
      (assert-equal current-context inner-ctx "Current should be inner context")
      (print-string "  PASSED")

      ; Test 13: Method return
      (print-string "Test 13: Method return")
      (define-var return-val (method-return (tag-int 999)))
      (assert-equal (untag-int return-val) 999 "Return value should be 999")
      (assert-equal current-context outer-ctx "Should restore outer context")
      (print-string "  PASSED")

      ; Test 14: Return to NULL (end of chain)
      (print-string "Test 14: Return to NULL (end of chain)")
      (define-var final-return (method-return (tag-int 777)))
      (assert-equal (untag-int final-return) 777 "Final return value should be 777")
      (assert-equal current-context NULL "Should restore to NULL context")
      (print-string "  PASSED")
      (print-string "")

      (print-string "=== Testing Symbol Table ===")
