      (print-string "Test 1: SmallInteger method lookup")
      (define-var int-val (tag-int 42))
      (assert-equal (is-int int-val) 1 "42 should be tagged int")
      (define-var int-class (get-class int-val))
      (assert-equal int-class SmallInteger-class "42 class should be SmallInteger")
      (assert-equal (untag-int (get-name int-class)) 5 "SmallInteger class name should be 5")
      (define-var add-method (lookup-method int-val (tag-int 40)))
      (assert-equal (untag-int add-method) 50000 "Should find SmallInteger + override")
      (print-string "  PASSED")
      (print-string "")

      (print-string "Test 2: SmallInteger inherited method")
      (define-var lt-method (lookup-method int-val (tag-int 30)))
      (assert-equal (untag-int lt-method) 30000 "Should find < from Magnitude")
      (print-string "  PASSED")
      (print-string "")

      (print-string "Test 3: SmallInteger from Object")
      (define-var eq-method (lookup-method int-val (tag-int 20)))
      (assert-equal (untag-int eq-method) 20000 "Should find == from Object")
      (print-string "  PASSED")
      (print-string "")

      (print-string "Test 4: SmallInteger from ProtoObject")
      (define-var class-method (lookup-method int-val (tag-int 10)))
      (assert-equal (untag-int class-method) 10000 "Should find class from ProtoObject")
      (print-string "  PASSED")
      (print-string "")

      (print-string "Test 5: Point instance")
      (define-var p (new-instance Point 2 0))
      (assert-true (> p 0) "Point instance should have valid address")
      (assert-equal (is-int p) 0 "Point instance should not be tagged int")
      (assert-equal (is-oop p) 1 "Point instance should be OOP")
      (define-var x-method (lookup-method p (tag-int 80)))
      (assert-equal (untag-int x-method) 80000 "Should find x method from Point")
      (print-string "  PASSED")
      (print-string "")

      (print-string "Test 6: Point inherited from Object")
      (define-var p-eq-method (lookup-method p (tag-int 20)))
      (assert-equal (untag-int p-eq-method) 20000 "Point should inherit == from Object")
      (print-string "  PASSED")
      (print-string "")

      (print-string "Test 7: Array instance")
      (define-var arr (new-instance Array 0 70))
      (define-var at-method (lookup-method arr (tag-int 70)))
      (assert-equal (untag-int at-method) 70000 "Should find at: method from Array")
      (define-var size-method (lookup-method arr (tag-int 60)))
      (assert-equal (untag-int size-method) 60000 "Should find size from Collection")
      (print-string "  PASSED")
      (print-string "")

      (print-string "Test 8: Complete inheritance chain")
      (define-var si (tag-int 100))
      (define-var l1 (lookup-method si (tag-int 50)))
      (assert-equal (untag-int l1) 54000 "Level 1: SmallInteger bitAnd:")
      (define-var l2 (lookup-method si (tag-int 40)))
      (assert-equal (untag-int l2) 50000 "Level 2: Number +")
      (define-var l3 (lookup-method si (tag-int 30)))
      (assert-equal (untag-int l3) 30000 "Level 3: Magnitude <")
      (define-var l4 (lookup-method si (tag-int 20)))
      (assert-equal (untag-int l4) 20000 "Level 4: Object ==")
      (define-var l5 (lookup-method si (tag-int 10)))
      (assert-equal (untag-int l5) 10000 "Level 5: ProtoObject class")
      (print-string "  PASSED: 5-level inheritance chain working")
      (print-string "")
